### ISSUE TITLE
Hidden field removes itself

### ISSUE THREAD

**Issue by toleabivol** [wpninjas/ninja-forms#3513]
Hello,
I add a hidden field to an existing form and when I click on edit button next to it (gears) the edit tab appears but the field itself is being removed from the form (I see it visually) - It's like clicking on delete button next to edit button. So I end up with an edit pane open but without the actual field. Even if I save the edits it won't appear. 
Scenario 2 : When I add a hidden field then click publish , after a small delay the field disappears.
Scenario 3: adding 2 or more hidden fields does not help (they all disappear when I click publish).
This doesn't happen with other types of fields.
No errors in console. Last version of all : WP(4.9.5) and other plugins and ninja forms (3.2.23)

**Comment by toleabivol** [comment]
UPDATE: if I inspect the form in the editor/dashboard I can see the fields in there. Also in the merge tags I can see them.

**Comment by toleabivol** [comment]
UPDATE 2: OK I see , it get's hidden by css because it receives the css class `hidden` :)

**Comment by jmcelhaney** [comment]
I was able to confirm this issue. https://goo.gl/uL4hQm

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5ae30a5fdd8edd530e7f2b09/event/5ae30a5fdd8edd0b977f2b0c

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5ae70e83b6cee446c28b6523/event/5ae70e83dd8edd140da1d2bb

**Comment by jmcelhaney** [comment]
https://wpninjas.kustomerapp.com/app/customers/5ae63647c2fd3f7c54f3a943/event/5ae636471f94dc6c62b79127

**Comment by Much2tall** [comment]
Resolved by 3.2.24.

**Comment by dewezlopez** [comment]
Hi @Much2tall, I just updated to 3.3.3 and this issue is still present. Hidden fields become hidden once you click the settings symbol ⚙
